# Generated by Django 5.1.4 on 2025-02-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutstandingToken',
        ),
    ]
